### ISSUE TITLE
Erlang 20 is unsupported

### ISSUE THREAD

**Issue by Sitch** [hansihe/html5ever_elixir#7]
Running the latest version of html5ever (0.4.0).  Upgraded to erlang 20 and got a compilation error on ubuntu 16.04.  Stack trace from running `mix deps.compile html5ever`:

```
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
   Compiling erlang_nif-sys v0.6.1
   Compiling rustler_codegen v0.14.0
   Compiling html5ever v0.16.0
   Compiling string_cache v0.5.0
error: failed to run custom build command for `erlang_nif-sys v0.6.1`
process didn't exit successfully: `/root/m_c_a/_build/dev/rustler_crates/html5ever_nif/release/build/erlang_nif-sys-ae2db8d6f62d8a63/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.1/build.rs:28
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
could not compile dependency :html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile html5ever", update it with "mix deps.update html5ever" or clean it with "mix deps.clean html5ever"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:58: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:12: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
```

**Comment by hansihe** [comment]
This will be fixed once OTP20 lands in erlang_nif-sys

**Comment by hansihe** [comment]
Published a new version `0.5.0` which should work on OTP20.

**Comment by uranther** [comment]
Trying to compile `0.5.0` for OTP 20 and I get the following error. I am on Ubuntu 16.04 and I installed rustc and cargo via apt.

I can't figure out where to go from here. Adding `--verbose` doesn't seem to work.

```
==> html5ever
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
   Compiling phf_generator v0.7.21
   Compiling synom v0.11.3
   Compiling tendril v0.2.4
   Compiling erlang_nif-sys v0.6.2
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `erlang_nif-sys v0.6.2`
could not execute process `/mnt/2tb/programming/elixir/kie/_build/dev/rustler_crates/html5ever_nif/release/build/erlang_nif-sys-b31eae61802aa254/build-script-build` (never executed)

To learn more, run the command again with --verbose.
could not compile dependency :html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile html5ever", update it with "mix deps.update html5ever" or clean it with "mix deps.clean html5ever"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:62: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
```

**Comment by hansihe** [comment]
@uranther It looks like your rust compiler might be crashing. Could you try cloning this repo, going into the `native/html5ever_nif` directory and running `cargo build`?

**Comment by uranther** [comment]
That's weird. I posted a follow-up to the above but it doesn't seem to have saved.

I had two issues:

* Symlinks in the path break the Rust compiler
* I was using Rust 1.15 from apt repository

I solved it by moving the project directory out of symlinks and using the "preferred" `curl | sh` install method from the Rust website.

**Comment by joshuataylor** [comment]
I'm now seeing this in our project. Installing rust via `curl -sSf https://sh.rustup.rs | sh -s -- -y`, Elixir 1.6.0 .

I have to run:
```
cd deps/html5ever/native/html5ever_nif
cargo update
cargo build
```

For it to work.

**Comment by madawei2699** [comment]
@joshuataylor you is right, I solve this by install `curl -sSf https://sh.rustup.rs | sh -s -- -y` replace mac default rust. And it works!
